# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - hp-docs-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.0

      - name: Set up .NET Core
        uses: xt0rted/setup-dotnet@v1.5.0
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release --property PublishDir=${{env.DOTNET_ROOT}}/myapp

      - name: entiy framework install
        run: dotnet tool install -g dotnet-ef

      - name: entiy framework create migration
        run: dotnet ef migrations script --idempotent --startup-project Hp-Web-App.Client/Hp-Web-App.Client.csproj --output ${{env.DOTNET_ROOT}}/myapp/migrate.sql
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3.1.2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: Apply EF migration script
        uses: Azure/sql-action@v2.1
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTIONSTRING }}
          path: ${{env.DOTNET_ROOT}}/myapp/migrate.sql          

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hp-docs-app'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_317C72AEDB7B477FA5D79BCABE439EE5 }}
          package: .
